- id: futurize
  name: futurize
  description: Use python-future to ensure your Py2 code is runnable on Py3.
  language: python
  language_version: python3
  types: [python]
  entry: futurize -w -n --no-diffs
  args: [--stage1]
